language: android
dist: trusty

android:
  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-26
    - android-27
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew build

before_install:
  - chmod +x gradlew
  #  https://github.com/travis-ci/travis-ci/issues/8874
  - yes | sdkmanager "platforms;android-27"

branches:
  only:
    - master
